### ISSUE TITLE
g:NERDTreeGitStatusUpdateOnCursorHold

### ISSUE THREAD

**Issue by macOneOone** [Xuyuanp/nerdtree-git-plugin#157] opened 2020-08-23 22:36 UTC
#### Self-Diagnosis

- [x ] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation(README.md).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: MacOs Catalina
- [x] Vim/Neovim version `:echo v:version`: 802
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 
- [x] vimrc settings
    ```vim
    " all settings about nerdtree and other plugins
    ```
    - Other NERDTree-dependent Plugins
        - [x] jistr/vim-nerdtree-tabs
        - [x] ryanoasis/vim-devicons
        - [x] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Others (specify): 
    - [x] I've verified the issue occurs with only nerdtree-git-plugin installed.

#### Steps to Reproduce the Issue
1. After i update the option g:NERDTreeGitStatusUpdateOnCursorHold to 1 the warning remains to ask me for update
<img width="1096" alt="Captura de ecrã 2020-08-23, às 23 34 00" src="https://user-images.githubusercontent.com/16170629/90990413-2151fe00-e599-11ea-82fb-ee6d30636f7a.png">
<img width="454" alt="Captura de ecrã 2020-08-23, às 23 34 21" src="https://user-images.githubusercontent.com/16170629/90990422-30d14700-e599-11ea-84cf-67f1b0b1c69d.png">

**Comment by pedrolgcs** [comment] 2020-08-24 02:07
i have same problem

**Comment by Xuyuanp** [comment] 2020-08-24 03:00
Duplicate of #151

**Closed by Xuyuanp** 2020-08-24 03:00 UTC
Labels: bug
